### ISSUE TITLE
flake in Kind test: we enumerate from most to superkinds

### ISSUE THREAD

**Issue by johnynek** [johnynek/bosatsu#1123]
```
[info] - we enumerate from most to superkinds *** FAILED *** (14 minutes, 17 seconds)
[info]   StackOverflowError was thrown during property evaluation.
[info]     Message: "None"
[info]     Occurred when passed generated values (
[info]       arg0 = Cons(Arg(Invariant, Cons(Arg(Invariant, Cons(Arg(Covariant, Type), Type)), Cons(Arg(Covariant, Type), Type))), Cons(Arg(Phantom, Cons(Arg(Contravariant, Cons(Arg(Phantom, Type), Type)), Type)), Cons(Arg(Contravariant, Cons(Arg(Covariant, Cons(Arg(Covariant, Type), Type)), Cons(Arg(Invariant, Type), Type))), Cons(Arg(Phantom, Cons(Arg(Covariant, Type), Type)), Cons(Arg(Phantom, Type), Type)))))
[info]     )
```

**Comment by johnynek** [comment]
```
[info] - we enumerate from most to subkinds *** FAILED *** (1 second, 588 milliseconds)
[info]   JavaScriptException was thrown during property evaluation.
[info]     Message: RangeError: Maximum call stack size exceeded
[info]     Occurred when passed generated values (
[info]       arg0 = Cons(Arg(Phantom, Cons(Arg(Invariant, Cons(Arg(Covariant, Type), Type)), Cons(Arg(Phantom, Type), Type))), Cons(Arg(Invariant, Cons(Arg(Phantom, Cons(Arg(Invariant, Cons(Arg(Phantom, Type), Type)), Cons(Arg(Phantom, Type), Cons(Arg(Phantom, Type), Type)))), Cons(Arg(Invariant, Cons(Arg(Covariant, Type), Type)), Cons(Arg(Covariant, Type), Type)))), Cons(Arg(Invariant, Cons(Arg(Phantom, Type), Type)), Cons(Arg(Phantom, Type), Cons(Arg(Phantom, Type), Type)))))
[info]     )
```

**Comment by johnynek** [comment]
another example of flake:

```
==> X dev.bosatsu.KindParseTest.we enumerate from most to superkinds  517.356s munit.FailException: Failing seed: aFU18wbIDSFPn5duMElCaA4Lc6lgtL2SPE4HwVBdbhM=
You can reproduce this failure by adding the following override to your suite:

  override def scalaCheckInitialSeed = "aFU18wbIDSFPn5duMElCaA4Lc6lgtL2SPE4HwVBdbhM="

Exception raised on property evaluation.
> ARG_0: Cons(Arg(Covariant,Cons(Arg(Invariant,Cons(Arg(Phantom,Type),Type)),Cons(Arg(Invariant,Type),Type))),Cons(Arg(Phantom,Cons(Arg(Invariant,Cons(Arg(Phantom,Type),Cons(Arg(Invariant,Type),Type))),Cons(Arg(Contravariant,Cons(Arg(Phantom,Type),Type)),Cons(Arg(Invariant,Type),Type)))),Cons(Arg(Phantom,Type),Cons(Arg(Covariant,Type),Type))))
> Exception: java.lang.StackOverflowError: null
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:112)
Caused by: java.lang.StackOverflowError
    at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:144)
    at dev.bosatsu.Kind$$anon$2.hasNext(Kind.scala:170)
    at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:144)
    at dev.bosatsu.Kind$$anon$2.hasNext(Kind.scala:170)
    at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:144)
```
